### ISSUE TITLE
alpamon upgrade command is not working.

### ISSUE THREAD

**Issue by geunwoonoh** [alpacax/alpamon#13]
We need to fix the following error in alpamon upgrade command:

- When user tries to upgrade `alpamon` using the `alpamon upgrade` command, an error occurs. 

    - The `command history` in `alpacon-server` shows that the command exited with `exit status 100`.

**Comment by royroyee** [comment]
The issue has been resolved in the following commit : https://github.com/alpacanetworks/alpamon/commit/b80e2f5ed8b8526382f118e2c5bc563399acd132
